import Header from '@/components/header/header';
import './globals.css';
import Footer from '@/components/footer/footer';
import { Box, ChakraProvider } from '@chakra-ui/react';

export const metadata = {
	title: 'Hero',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<ChakraProvider>
					<Header />
					{children}
				</ChakraProvider>
			</body>
		</html>
	);
}
